### ISSUE TITLE
Should the project suppor Windows OS system

### ISSUE THREAD

**Issue by rubbishgod** [hirofumi0810/tensorflow_end2end_speech_recognition#1]
From some configs and several codes from train_***.py, I saw that the project is mainly developed in Linux system.
Could you please considerring the primitive project supporting Windows OS system. For example, the directory could not use relative directory instead of absolute directory like "/n/sd8/inaguma/result/timit/"?

**Comment by hirofumi0810** [comment]
Hi,

So, do you mean that you would like me to update for '\' ?
Then, I think it's good to replace '/' with os.sep.

**Comment by rubbishgod** [comment]
Yes.
Additionally, please use relative path like 'dataset/1/', other than the absolute path like '/home/rubbishgod/attention/dataset/1/'.
