### ISSUE TITLE
attention mechanism

### ISSUE THREAD

**Issue by wolverineq** [hirofumi0810/tensorflow_end2end_speech_recognition#7]
Hi I am a postgraduate student who majors in speech recognition. I appreicate your work here and am quite interested in your end-to-end project. I wonder how soon will attention mechanism come out (e.g. LAS model)?

**Comment by wolverineq** [comment]
I have tested run_attention.sh script and found that the decoder part is not done yet.

**Comment by hirofumi0810** [comment]
Hi,

I'm now refactoring them, so attention-based models do not work.
Please wait for a few weaks.

I'll complete them by the end of this month.
In fact, except beam search decoders, all have been already done.

Best,

Hirofumi




2017-09-15 10:42 GMT+09:00 wolverineq <notifications@github.com>:

**Comment by wolverineq** [comment]
Thanks for your reply!
